spring:
  application:
    name: programming-platform

  datasource:
    url: jdbc:postgresql://postgresql:5432/programing_platform_db
    username: ${DB_USERNAME}
#    postgres
    password: ${DB_PASSWORD}
#    5736
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    open-in-view: false
  mail:
    default-encoding: UTF-8
    host: smtp.ukr.net
    port: 465
    username: devspark@ukr.net
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            fallback: false
            class: javax.net.ssl.SSLSocketFactory

jwt:
  secret: mT7x59fDfFz$3kLpA1D@Lq9Vb02MzX3r
  expiration: 86400000

theory:
  html:
    directory: /storage/html/